import type { Locality, VenueCard, VenueDetail, AvailabilityResponse } from '@nexora/shared';

export const DEMO_LOCALITIES: Locality[] = [
  { id: 'loc-1', slug: 'cyber-city-gurgaon', name: 'Cyber City', city: 'Gurgaon', label: 'Cyber City, Gurgaon' },
  { id: 'loc-2', slug: 'koramangala-bangalore', name: 'Koramangala', city: 'Bangalore', label: 'Koramangala, Bangalore' },
  { id: 'loc-3', slug: 'bkc-mumbai', name: 'Bandra Kurla Complex', city: 'Mumbai', label: 'Bandra Kurla Complex, Mumbai' },
  { id: 'loc-4', slug: 'manhattan-nyc', name: 'Manhattan', city: 'New York', label: 'Manhattan, New York' },
];

export const DEMO_VENUES: Record<string, VenueCard[]> = {
  'cyber-city-gurgaon': [
    {
      id: 'a0000000-0000-0000-0000-000000000001',
      slug: 'ember-and-oak',
      name: 'Ember & Oak',
      localityId: 'loc-1',
      localityLabel: 'Cyber City, Gurgaon',
      address: 'DLF Cyber Hub, Tower B',
      cuisines: ['Modern Indian', 'Grill'],
      rating: 4.6,
      ratingCount: 2140,
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 140000,
      costForTwoPaise: 260000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '12:00', closeTime: '23:00' }],
    },
    {
      id: 'a0000000-0000-0000-0000-000000000002',
      slug: 'the-table',
      name: 'The Table Bistro',
      localityId: 'loc-1',
      localityLabel: 'Cyber City, Gurgaon',
      address: 'Cyber Hub, Ground Floor',
      cuisines: ['European', 'Contemporary'],
      rating: 4.7,
      ratingCount: 1840,
      imageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 160000,
      costForTwoPaise: 300000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '12:00', closeTime: '23:30' }],
    },
    {
      id: 'a0000000-0000-0000-0000-000000000003',
      slug: 'saffron-lane',
      name: 'Saffron Lane',
      localityId: 'loc-1',
      localityLabel: 'Cyber City, Gurgaon',
      address: 'Cyber City, Building 10',
      cuisines: ['North Indian', 'Mughlai'],
      rating: 4.3,
      ratingCount: 980,
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 90000,
      costForTwoPaise: 170000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '12:00', closeTime: '23:00' }],
    },
  ],
  'manhattan-nyc': [
    {
      id: 'a0000000-0000-0000-0000-000000000010',
      slug: 'hudson-river-grill',
      name: 'Hudson River Grill',
      localityId: 'loc-4',
      localityLabel: 'Manhattan, New York',
      address: 'Pier 57, Hudson River Park',
      cuisines: ['American', 'Steakhouse'],
      rating: 4.8,
      ratingCount: 1950,
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 4500,
      costForTwoPaise: 9000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '11:30', closeTime: '23:00' }],
    },
  ],
  'koramangala-bangalore': [
    {
      id: 'a0000000-0000-0000-0000-000000000004',
      slug: 'kinfolk-kitchen',
      name: 'Kinfolk Kitchen',
      localityId: 'loc-2',
      localityLabel: 'Koramangala, Bangalore',
      address: '80 Feet Rd, 4th Block',
      cuisines: ['Cafe', 'Continental'],
      rating: 4.5,
      ratingCount: 3120,
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 70000,
      costForTwoPaise: 130000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '08:00', closeTime: '22:00' }],
    },
    {
      id: 'a0000000-0000-0000-0000-000000000005',
      slug: 'umami-house',
      name: 'Umami House',
      localityId: 'loc-2',
      localityLabel: 'Koramangala, Bangalore',
      address: '5th Block, Jyoti Nivas College Rd',
      cuisines: ['Japanese', 'Sushi'],
      rating: 4.7,
      ratingCount: 1890,
      imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=70',
      costForOnePaise: 160000,
      costForTwoPaise: 300000,
      isOpenNow: true,
      acceptingBookings: true,
      todayHours: [{ openTime: '12:00', closeTime: '23:00' }],
    },
  ],
};

const DEFAULT_SHIFTS = [
  { dayOfWeek: 0, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 1, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 2, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 3, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 4, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 5, openTime: '12:00', closeTime: '23:00' },
  { dayOfWeek: 6, openTime: '12:00', closeTime: '23:00' },
];

export const DEMO_VENUE_DETAILS: Record<string, VenueDetail> = {
  'the-table': {
    ...DEMO_VENUES['cyber-city-gurgaon'][1],
    description: 'Contemporary European small plates, bespoke cocktails, and live acoustic lounge.',
    timezone: 'Asia/Kolkata',
    turnaroundMins: 90,
    gracePeriodMins: 15,
    shifts: DEFAULT_SHIFTS,
  },
  'ember-and-oak': {
    ...DEMO_VENUES['cyber-city-gurgaon'][0],
    description: 'Wood-fired Indian small plates and a curated whisky list.',
    timezone: 'Asia/Kolkata',
    turnaroundMins: 90,
    gracePeriodMins: 15,
    shifts: DEFAULT_SHIFTS,
  },
  'hudson-river-grill': {
    ...DEMO_VENUES['manhattan-nyc'][0],
    description: 'Prime dry-aged steaks, fresh Atlantic seafood, and sunset skyline views.',
    timezone: 'America/New_York',
    turnaroundMins: 90,
    gracePeriodMins: 15,
    shifts: DEFAULT_SHIFTS,
  },
};
